# Generated by Django 2.1 on 2018-09-12 11:26

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('author', models.CharField(help_text='Author of the action. Is username or System.', max_length=64)),
                ('actor', models.CharField(blank=True, help_text='This must contains the username of the actor when an action is performed.', max_length=64, null=True)),
                ('action', models.CharField(help_text='Action performed.', max_length=64)),
                ('system', models.CharField(help_text='Source application that action comes from. E.g: Platform, Olms', max_length=64)),
                ('content_type', models.CharField(blank=True, help_text='Model Name.', max_length=64, null=True)),
                ('object_pk', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('extra', models.TextField(blank=True, help_text='Json Field. Useful to store the serializable target object ', null=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
